/**
 * Generated by `npm run art:photos` — do not edit by hand.
 *
 * Technical data about the processed scrapbook images. Captions and ordering
 * live in `content.ts`; this file only records what each photo's dimensions and
 * available widths are, so the component can build a srcset and reserve the
 * right space before the image loads.
 */

export type ScrapbookImage = {
  /** Intrinsic size of the largest generated width, used for aspect ratio. */
  width: number
  height: number
  /** Widths available as `/images/scrapbook/<slug>-<width>.webp`. */
  widths: number[]
}

export const scrapbookImages: Record<string, ScrapbookImage> = {
  "Christmas_2019": {
    "width": 720,
    "height": 960,
    "widths": [
      480,
      720
    ]
  },
  "Covid_Highschool": {
    "width": 1080,
    "height": 1996,
    "widths": [
      480,
      720,
      1080
    ]
  },
  "Engaged_Photo": {
    "width": 1600,
    "height": 2133,
    "widths": [
      480,
      720,
      1080,
      1600
    ]
  },
  "Grad_23": {
    "width": 720,
    "height": 1080,
    "widths": [
      480,
      720
    ]
  },
  "Kayaking": {
    "width": 1080,
    "height": 1920,
    "widths": [
      480,
      720,
      1080
    ]
  },
  "Lexis_18_24": {
    "width": 1600,
    "height": 1200,
    "widths": [
      480,
      720,
      1080,
      1600
    ]
  },
  "The_Arches_230522": {
    "width": 1080,
    "height": 1440,
    "widths": [
      480,
      720,
      1080
    ]
  }
}
