import { mkdir, readdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'

/**
 * Turns the original scrapbook photos into responsive WebP images.
 *
 * Drop originals into `photos/` (jpg, jpeg, png, heic, webp) and run this. The
 * filename becomes the slug used in `content.ts`, so `photos/first-date.jpg`
 * is listed there as `slug: 'first-date'`.
 *
 * Each photo is written at several widths so browsers download only what they
 * need, and a manifest is generated with the dimensions so the layout can
 * reserve space and avoid shifting as images load.
 */

const SOURCE_DIR = 'photos'
const OUT_DIR = 'public/images/scrapbook'
const MANIFEST = 'src/lib/scrapbookImages.ts'

/** Displayed at roughly 320-520px, so these cover 1x through 3x screens. */
const WIDTHS = [480, 720, 1080, 1600]

const SUPPORTED = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif', '.tiff'])

let files = []
try {
  files = await readdir(SOURCE_DIR)
} catch {
  console.log(`No ${SOURCE_DIR}/ folder yet. Create it and add photos, then run this again.`)
  process.exit(0)
}

const photos = files.filter((f) => SUPPORTED.has(path.extname(f).toLowerCase()))

if (photos.length === 0) {
  console.log(`No images found in ${SOURCE_DIR}/. Supported: ${[...SUPPORTED].join(', ')}`)
  process.exit(0)
}

await mkdir(OUT_DIR, { recursive: true })

const manifest = {}

for (const file of photos.sort()) {
  const slug = path.basename(file, path.extname(file))
  const input = path.join(SOURCE_DIR, file)

  // rotate() with no argument applies the EXIF orientation, so phone photos
  // are not written sideways.
  const source = sharp(input).rotate()
  const meta = await source.metadata()
  const sourceWidth = meta.autoOrient?.width ?? meta.width
  const sourceHeight = meta.autoOrient?.height ?? meta.height

  const widths = WIDTHS.filter((w) => w <= sourceWidth)
  if (widths.length === 0) widths.push(sourceWidth)

  let largest = { width: sourceWidth, height: sourceHeight }

  for (const width of widths) {
    const out = path.join(OUT_DIR, `${slug}-${width}.webp`)
    const info = await sharp(input)
      .rotate()
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: 78 })
      .toFile(out)
    if (width === widths.at(-1)) largest = { width: info.width, height: info.height }
    console.log(`${out}  ${info.width}x${info.height}  ${Math.round(info.size / 1024)} KB`)
  }

  manifest[slug] = { width: largest.width, height: largest.height, widths }
}

const body = `/**
 * Generated by \`npm run art:photos\` — do not edit by hand.
 *
 * Technical data about the processed scrapbook images. Captions and ordering
 * live in \`content.ts\`; this file only records what each photo's dimensions and
 * available widths are, so the component can build a srcset and reserve the
 * right space before the image loads.
 */

export type ScrapbookImage = {
  /** Intrinsic size of the largest generated width, used for aspect ratio. */
  width: number
  height: number
  /** Widths available as \`/images/scrapbook/<slug>-<width>.webp\`. */
  widths: number[]
}

export const scrapbookImages: Record<string, ScrapbookImage> = ${JSON.stringify(manifest, null, 2)}
`

await writeFile(MANIFEST, body)

console.log(`\n${photos.length} photo(s) processed. Slugs for content.ts:`)
for (const slug of Object.keys(manifest)) console.log(`  ${slug}`)
